# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='tytuł')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('street_address2', models.CharField(blank=True, max_length=255, verbose_name='adres (kontynuacja)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='miasto')),
                ('country', models.CharField(blank=True, choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('LT', 'Litwa')], max_length=2, verbose_name='kraj')),
                ('latitude', models.FloatField(blank=True, help_text='Szerokość geograficzna to kąt zawarty między dowolnym punktem a równikiem(biegun północny maszerokość geograficzną 90, a południowy — -90).', null=True, verbose_name='szerokość geograficzna')),
                ('longitude', models.FloatField(blank=True, help_text='Długość geograficzna to kąt zawarty między dowolnnym punktem na Ziemi a południkiem 0przechodzącym przez park w Greenwich w Wielkiej Brytanii. Na wschód od południka 0 położone są punkty o długości geograficznej wschodniej, a na zachód — punkty o długości geograficznej zachodniej.', null=True, verbose_name='długość geograficzna')),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
            },
        ),
    ]
