# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FaP', '0002_serials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Data i godzina utworzenia')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Data i godzina modyfikacji')),
                ('object_id', models.CharField(default='', help_text='Podaj identyfikator powiązanego obiektu.', max_length=255, verbose_name='Powiązany obiekt')),
                ('content_type', models.ForeignKey(help_text='Wybierz typ (model) relacji, którą chcesz zbudować.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Typ (model) powiązanego obiektu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'polubienia',
                'ordering': ('-created',),
                'verbose_name': 'polubienie',
            },
        ),
    ]
