# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 18:43
from __future__ import unicode_literals

import FaP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaP', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=FaP.models.upload_to, verbose_name='photo')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaP.Movie')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
