# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Data i godzina utworzenia')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Data i godzina modyfikacji')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mptt.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['tree_id', 'lft'],
                'verbose_name_plural': 'Categories',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Data i godzina utworzenia')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Data i godzina modyfikacji')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('categories', mptt.fields.TreeManyToManyField(to='Mptt.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
