# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:05
from __future__ import unicode_literals

import apps.search_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=apps.search_app.models.upload_path)),
                ('url_source', models.URLField(max_length=128)),
                ('url_name', models.TextField(max_length=128)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
