# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('?',), 'verbose_name': 'Applications', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='url_name',
            field=models.CharField(blank=True, choices=[('change_styling', 'change_styling'), ('search_app', 'search_app'), ('tree_traversal', 'tree_traversal')], max_length=128),
        ),
    ]
