# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20170216_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='url_name',
            field=models.CharField(blank=True, choices=[('change_styling', 'change_styling'), ('codility', 'codility'), ('search_app', 'search_app'), ('tree_traversal', 'tree_traversal'), ('__pycache__', '__pycache__')], max_length=128),
        ),
    ]
