# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20170306_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='url_name',
            field=models.CharField(choices=[('change_styling', 'change_styling'), ('codility', 'codility'), ('julia_set', 'julia_set'), ('mpl_graph', 'mpl_graph'), ('scikit_chart', 'scikit_chart'), ('search_app', 'search_app'), ('tree_traversal', 'tree_traversal'), ('wallpaper', 'wallpaper')], max_length=128, unique=True),
        ),
    ]
