# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 07:27
from __future__ import unicode_literals

import Import_And_Export.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Import_And_Export', '0002_auto_20160403_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nazwa')),
                ('artist', models.CharField(max_length=250, verbose_name='Artysta')),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Import_And_Export.models.upload_to, verbose_name='Obraz')),
            ],
            options={
                'verbose_name_plural': 'Ścieżki',
                'verbose_name': 'Ścieżka',
            },
        ),
    ]
