# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodilityTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('annotation', models.CharField(max_length=256)),
                ('code', models.TextField()),
                ('link', models.URLField(max_length=128)),
            ],
        ),
    ]
